---
codfw_migrate:
  bgp:
    evpn_as: 65187
    rr_cluster: 1.1.1.1

  vlans:
    VLAN100:
      id: 100
      anycast_gw: 
        ipv4: "10.192.0.1"
        ipv6: "2620:0:860:101::1"
    VLAN200:
      id: 200
    VLAN300:
      id: 300

  anycast_neighbors:
    server1: 10.192.0.11
    server2: 10.192.0.12

  default_instance: WMF_PROD
  routing_instances:
    WMF_PROD:
      vni: 5000
      dynamic_bgp: {}
#        groups:
#          DYNAMIC_PEERS:
#            export: "DEFAULT_EVPN"
#            peer_as: 64600
#            md5: "$9$5T6AB1hrK8EcVw2gJZ69C" # test123

  # Listed here so Homer has access when generating configs for all devices,
  # allowing us to set up loopbacks of other switches as EVPN iBGP peers.
  devices:
    CORE1:
      role: core
      loopback: 208.80.153.192
    CORE2:
      role: core
      loopback: 208.80.153.193
    SPINE1:
      role: spine
      loopback: 1.1.1.1
    SPINE2:
      role: spine
      loopback: 2.2.2.2
    LEAF1:
      role: leaf
      loopback: 11.11.11.11
    LEAF2:
      role: leaf
      loopback: 12.12.12.12

  links:
    - nodes:
        SPINE1: "xe-0/0/0"
        LEAF1: "xe-0/0/0"
      v4_prefix: "10.1.1.0/31"

    - nodes:
        SPINE1: "xe-0/0/1"
        LEAF2: "xe-0/0/0"
      v4_prefix: "10.2.1.0/31"

    - nodes:
        SPINE2: "xe-0/0/0"
        LEAF1: "xe-0/0/1"
      v4_prefix: "10.1.2.0/31"

    - nodes:
        SPINE2: "xe-0/0/1"
        LEAF2: "xe-0/0/1"
      v4_prefix: "10.2.2.0/31"

