---
dnslab:
  bgp:
    evpn_as: 65187
    rr_cluster: 1.1.1.1

  devices:
    CORE1:
      role: core
      loopback: 10.10.10.10
    CORE2:
      role: core
      loopback: 20.20.20.20
    SPINE1:
      role: spine
      loopback: 1.1.1.1
    SPINE2:
      role: spine
      loopback: 2.2.2.2
    LEAF1:
      role: leaf
      loopback: 11.11.11.11
    LEAF2:
      role: leaf
      loopback: 12.12.12.12
    LEAF3:
      role: leaf
      loopback: 13.13.13.13

  links:
    - nodes:
        SPINE1: "eth1"
        LEAF1: "eth1"
      v4_prefix: "10.1.1.0/31"

    - nodes:
        SPINE1: "eth2"
        LEAF2: "eth1"
      v4_prefix: "10.2.1.0/31"

    - nodes:
        SPINE1: "eth3"
        LEAF3: "eth1"
      v4_prefix: "10.3.1.0/31"

    - nodes:
        SPINE2: "eth1"
        LEAF1: "eth2"
      v4_prefix: "10.1.2.0/31"

    - nodes:
        SPINE2: "eth2"
        LEAF2: "eth2"
      v4_prefix: "10.2.2.0/31"

    - nodes:
        SPINE2: "eth3"
        LEAF3: "eth2"
      v4_prefix: "10.3.2.0/31"

    - nodes:
        LEAF1: "eth3"
        SERVER1: "eth1"
      v4_prefix: "10.10.1.0/31"

    - nodes:
        LEAF2: "eth3"
        SERVER2: "eth1"
      v4_prefix: "10.10.2.0/31"

    - nodes:
        SPINE1: "eth4"
        CORE1: "eth2"
      v4_prefix: "10.20.1.0/31"

    - nodes:
        SPINE2: "eth4"
        CORE2: "eth2"
      v4_prefix: "10.20.2.0/31"

