CORE1:
  role: core
  site: eqiadlab
  config:
    ip_ints:
      "ge-0/0/0":
        descr: "CORE2 ge-0/0/1"
        ipv4: "198.18.11.0/31"
      "ge-0/0/1":
        descr: "SPINE1 xe-0/0/3"
        subints:
          100:
            descr: "SPINE1 WMF_PROD VRF"
            ipv4: "100.64.100.0/31"

CORE2:
  role: core
  site: eqiadlab
  config:
    ip_ints:
      "ge-0/0/0":
        descr: "CORE1 ge-0/0/1"
        ipv4: "198.18.11.1/31"
      "ge-0/0/1":
        descr: "SPINE2 xe-0/0/3"
        subints:
          100:
            descr: "SPINE2 WMF_PROD VRF"
            ipv4: "100.64.100.2/31"

SPINE1:
  role: spine
  site: eqiadlab
  config:
    ip_ints:
      "xe-0/0/3":
        descr: "CORE1 ge-0/0/1"
        subints:
          100:
            ipv4: "100.64.100.1/31"

SPINE2:
  role: spine
  site: eqiadlab
  config:
    ip_ints:
      "xe-0/0/3":
        descr: "CORE2 ge-0/0/1"
        subints:
          100:
            ipv4: "100.64.100.3/31"

LEAF1:
  role: leaf
  site: eqiadlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server1
          vlan: VLAN100
    vlan_ints:
      VLAN100:
        ipv4: "198.18.100.1/24"
        ipv6: "2001:0470:6a7f:0100::1/64"
      
LEAF2:
  role: leaf
  site: eqiadlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server2
          vlan: VLAN100
    vlan_ints:
      VLAN100:
        ipv4: "198.18.100.2/24"
        ipv6: "2001:0470:6a7f:0100::2/64"

LEAF3:
  role: leaf
  site: eqiadlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server3
          vlan: VLAN200
    vlan_ints:
      VLAN200:
        ipv4: "198.18.200.254/24"
        ipv6: "2001:0470:6a7f:0200::254/64"
    
    
