SPINE1:
  role: spine
  site: rrlab

SPINE2:
  role: spine
  site: rrlab

SPINE3:
  role: spine
  site: rrlab

SPINE4:
  role: spine
  site: rrlab

LEAF1:
  role: leaf
  site: rrlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server1
          vlan: VLAN100
    vlan_ints:
      VLAN100:
        ipv4: "198.18.100.1/24"
        ipv6: "2001:0470:6a7f:0100::1/64"
      
LEAF2:
  role: leaf
  site: rrlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server2
          vlan: VLAN200
    vlan_ints:
      VLAN200:
        ipv4: "198.18.200.1/24"
        ipv6: "2001:0470:6a7f:0200::1/64"

