CORE1:
  role: core
  site: evpnlab
  config:
    device_bgp:
      groups:
        SWITCH_CR:
          export: DEFAULT-OUT
          peers:
            "100.64.1.0":
              descr: SPINE1
              peer_as: 65187
        IBGP:
          type: internal
          export: ALLOW-ALL
          peers:
            "100.64.0.0":
              descr: CORE2
              peer_as: 14907

CORE2:
  role: core
  site: evpnlab
  config:
    device_bgp:
      groups:
        SWITCH_CR:
          export: DEFAULT-OUT
          peers:
            "100.64.2.0":
              descr: SPINE2
              peer_as: 65187
        IBGP:
          type: internal
          export: ALLOW-ALL
          peers:
            "100.64.0.1":
              descr: CORE1
              peer_as: 14907

SPINE1:
  role: spine
  site: evpnlab
  config:
    device_bgp:
      routing_instance:
        WMF_PROD:
          groups:
            CORE_ROUTERS:
              export: "EXT_OUT"
              peers:
                "100.64.1.1":
                  descr: CR1
                  peer_as: 14907
#          v6_groups:
#            CORE_ROUTERS_V6:
#              export: "EXTV6_OUT"
#              peers:
#                "2001:0470:6a7f:0083::1":
#                  descr: CR1
#                  peer_as: 14907

SPINE2:
  role: spine
  site: evpnlab
  config:
    device_bgp:
      routing_instance:
        WMF_PROD:
          groups:
            CORE_ROUTERS:
              export: "EXT_OUT"
              peers:
                "100.64.2.1":
                  descr: CR1
                  peer_as: 14907

LEAF1:
  role: leaf
  site: evpnlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server1
          vlan: VLAN100
    vlan_ints:
      VLAN100:
        ipv4: "198.18.100.1/24"
        ipv6: "2001:0470:6a7f:0100::1/64"
      
LEAF2:
  role: leaf
  site: evpnlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server2
          vlan: VLAN100
    vlan_ints:
      VLAN100:
        ipv4: "198.18.100.2/24"
        ipv6: "2001:0470:6a7f:0100::2/64"

LEAF3:
  role: leaf
  site: evpnlab
  config:
    vlan_ports:
      access:
        "xe-0/0/2":
          descr: server3
          vlan: VLAN101
    vlan_ints:
      VLAN101:
        ipv4: "198.18.101.254/24"
        ipv6: "2001:0470:6a7f:0101::254/64"
