---
evpnlab:
  bgp:
    evpn_as: 65187
    rr_cluster: 1.1.1.1

  vlans:
    VLAN100:
      id: 100
      anycast_gw: 
        ipv4: "198.18.100.254"
        ipv6: "2001:0470:6a7f:0100::254"
    VLAN200:
      id: 200

  default_instance: WMF_PROD
  routing_instances:
    WMF_PROD:
      vni: 5000
      dynamic_bgp:
        groups:
          DYNAMIC_PEERS:
            export: "DEFAULT_EVPN"
            peer_as: 64600
            md5: "$9$5T6AB1hrK8EcVw2gJZ69C" # test123

  devices:
    SPINE1:
      role: spine
      loopback: 1.1.1.1
    SPINE2:
      role: spine
      loopback: 2.2.2.2
    LEAF1:
      role: leaf
      loopback: 11.11.11.11
    LEAF2:
      role: leaf
      loopback: 12.12.12.12
    LEAF3:
      role: leaf
      loopback: 13.13.13.13
    LEAF4:
      role: leaf
      loopback: 14.14.14.14

  links:
    - nodes:
        SPINE1: "xe-0/0/0"
        LEAF1: "xe-0/0/0"
      v4_prefix: "10.1.1.0/31"

    - nodes:
        SPINE1: "xe-0/0/1"
        LEAF2: "xe-0/0/0"
      v4_prefix: "10.2.1.0/31"

    - nodes:
        SPINE1: "xe-0/0/2"
        LEAF3: "xe-0/0/0"
      v4_prefix: "10.3.1.0/31"

    - nodes:
        SPINE2: "xe-0/0/0"
        LEAF1: "xe-0/0/1"
      v4_prefix: "10.1.2.0/31"

    - nodes:
        SPINE2: "xe-0/0/1"
        LEAF2: "xe-0/0/1"
      v4_prefix: "10.2.2.0/31"

    - nodes:
        SPINE2: "xe-0/0/2"
        LEAF3: "xe-0/0/1"
      v4_prefix: "10.3.2.0/31"

